### ISSUE TITLE
Any chance to update to Idea 2022.3.2

### ISSUE THREAD

**Issue by rtiedema** [nek4life/sfcc-studio#121]
This plugin is amazing. But after changing my computer and having an fresh install of Idea I'm not able to install the plugin anymore.

My colleague has the same Idea version und runs the plugin successfully. But he has started from an older Idea and has used the Idea update mechanism. With this the plugin remains working.

Any chance?

**Comment by orvischoinierec** [comment]
@rtiedema let me take a look. The plugin should work with 2022.3.2. The 2023 version of the plugin will not work at this point as the 2023 series is in EAP phase, and I do not have a build for this year yet.

What version of Idea are you running? 2023.3.2 isn't out yet. That would be the 3rd release of this year.

**Comment by nek4life** [comment]
@rtiedema let me take a look. The plugin should work with 2022.3.2. The 2023 version of the plugin will not work as the 2023 series is in EAP phase, and I do not have a build for this year yet.

What version of Idea are you running? 2023.3.2 isn't out yet. That would be the 3rd release of this year.

**Comment by rtiedema** [comment]
Sorry, of course I meant 2022.3.2. Meanwhile I have set the pluginUntilBuild in gradle.properties to "223.*" and it is working now.

**Comment by nek4life** [comment]
@rtiedema, yes that is what needs to happen. In the past, the plugin didn't have an untilBuild settings, but when I moved to the new recommended plugin template, that is enforced. That means every time there is a new version the plugin needs to be rebuilt. I try to get to it as soon as I can, but unfortunately, it isn't always when there is a new release. 

I would be happy to take a pull request updating the plugin so that everyone can enjoy the update.

Charlie

**Comment by nek4life** [comment]
I published a new update to the plugin repository. Please let me know if you are still having this issue. I updated the new untilBuild to support the upcoming 2023.1 release
