### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by khsadira** [nek4life/sfcc-studio#23]
Hello ! Awesome job for your plugin, but I have one little issue.

I tried to use the plugin behind the proxy of my work and it doesn't work, do you have any ide of how can I make it work properly ?

We tried, with my admin sys, to see where the problem is, and after some point, we found that it's probably from the plugin, but maybe I didn't enable something like "authorize plugin to use proxy setting" or something like.

(my proxy is working with intellij, I tried to reach my sandbox with the check-connection in proxy settings, and it's work, and I can download plugin etc...)

Feel free to ask me if I did any basic configuration step to enable something related to my problem on intellij, I'm new with this IDE. 😄 

Thanks !

**Comment by nek4life** [comment]
Hi @khsadira. Glad to hear you like the plugin. I have tried to add proxy support to the plugin and I'm wondering if you could test it out. 

I'm working on the new 2020.1 EAP so you will need to install the latest EAP version of Intellij. You can either use the toolbox plugin and change the release channel or download direct https://www.jetbrains.com/idea/nextversion/

Once you have done that you can go the plugin page and add a custom plugin repository

https://plugins.jetbrains.com/plugins/eap/list 

This will add the EAP channel for the plugin which has this feature. If you can't get this to work you can also find the EAP version and download direct from my plugin page by switching to EAP https://plugins.jetbrains.com/plugin/11590-salesforce-commerce-cloud-studio/versions 1.6.1-SNAPSHOT.

I have not been able to test this myself yet since I do not have a proxy to work with, so I was hoping maybe you could help me out. If it still doesn't work I can look further into setting up a local proxy so I can test. Thanks!

**Comment by khsadira** [comment]
Hi @nek4life, sorry for the long period without any answers, I was far from office haha !

I followed yours instructions, and it's currently working well.
Thank you a lot again for your fix, and for this awesome plugin !!

**Comment by nek4life** [comment]
Great! Glad to hear that it is working now!
